apps/skateboard/web/router.ex
defmodule Skateboard.Router do
  use Skateboard.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Skateboard do
    pipe_through :browser # Use the default browser stack
    resources "/registrations", RegistrationController, only: [:new, :create]
    get    "/login",  SessionController, :new
    post   "/login",  SessionController, :create
    delete "/logout", SessionController, :delete
    get    "/",       PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", Skateboard do
  #   pipe_through :api
  # end
end

apps/skateboard/lib/skateboard/endpoint.ex
defmodule Skateboard.Endpoint do
  use Phoenix.Endpoint, otp_app: :skateboard

  socket "/socket", Skateboard.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :skateboard, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  #if code_reloading? do
    #socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    #plug Phoenix.LiveReloader
    #plug Phoenix.CodeReloader
  #end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_skateboard_key",
    signing_salt: "a0ltCPuM"

  plug Skateboard.Router
end

apps/skateboard/lib/skateboard/repo.ex
defmodule Skateboard.Repo do
  use Ecto.Repo, otp_app: :skateboard
end

apps/skateboard/web/models/event.ex
defmodule Skateboard.Event do
  use Skateboard.Web, :model

  schema "events" do
    field :user_id, :integer
    field :game_id, :string
    field :score, :integer
    field :winner, :boolean, default: false

    timestamps
  end

  @required_fields ~w(user_id game_id score winner)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

apps/skateboard/web/models/registration.ex
defmodule Skateboard.Registration do
  import Ecto.Changeset, only: [put_change: 3]

  def create(changeset, repo) do
    changeset
    |> put_change(:crypted_password, hashed_password(changeset.params["password"]))
    |> repo.insert()
  end

  defp hashed_password(password) do
    Comeonin.Bcrypt.hashpwsalt(password)
  end
end

apps/skateboard/web/models/session.ex
defmodule Skateboard.Session do
  alias Skateboard.User

  def current_user(conn) do
    id = Plug.Conn.get_session(conn, :current_user)
    if id, do: Skateboard.Repo.get(User, id)
  end

  def logged_in?(conn), do: !!current_user(conn)

  def login(params, repo) do
    user = repo.get_by(User, name: params["name"])
    case authenticate(user, params["password"]) do
      true -> {:ok, user}
      _    -> :error
    end
  end

  defp authenticate(user, password) do
    case user do
      nil -> false
      _   -> Comeonin.Bcrypt.checkpw(password, user.crypted_password)
    end
  end
end

apps/skateboard/web/models/user.ex
defmodule Skateboard.User do
  use Skateboard.Web, :model

  schema "users" do
    field :name, :string
    field :crypted_password, :string
    field :password, :string, virtual: true
    timestamps
  end

  @required_fields ~w(name password)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> unique_constraint(:name)
  end
end

apps/skateboard/web/controllers/page_controller.ex
defmodule Skateboard.PageController do
  use Skateboard.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

apps/skateboard/web/controllers/registration_controller.ex
defmodule Skateboard.RegistrationController do
  use Skateboard.Web, :controller
  alias Skateboard.User

  def new(conn, _params) do
    changeset = User.changeset(%User{})
    render conn, changeset: changeset
  end

  def create(conn, %{"user" => user_params}) do
    changeset = User.changeset(%User{}, user_params)

    case Skateboard.Registration.create(changeset, Skateboard.Repo) do
      {:ok, changeset} ->
        conn
        |> put_session(:current_user, changeset.id)
        |> put_flash(:info, "Your account was created")
        |> redirect(to: "/")
      {:error, changeset} ->
        conn
        |> put_flash(:info, "Unable to create account")
        |> render("new.html", changeset: changeset)
    end
  end
end

apps/skateboard/web/controllers/session_controller.ex
defmodule Skateboard.SessionController do
  use Skateboard.Web, :controller

  def new(conn, _params) do
    render conn, "new.html"
  end

  def create(conn, %{"session" => session_params}) do
    case Skateboard.Session.login(session_params, Skateboard.Repo) do
      {:ok, user} ->
        conn
        |> put_session(:current_user, user.id)
        |> put_flash(:info, "Logged in")
        |> redirect(to: "/")
      :error ->
        conn
        |> put_flash(:info, "Wrong name or password")
        |> render("new.html")
    end
  end

  def delete(conn, _) do
    conn
    |> delete_session(:current_user)
    |> put_flash(:info, "Logged out")
    |> redirect(to: "/")
  end
end

apps/skateboard/web/views/error_view.ex
defmodule Skateboard.ErrorView do
  use Skateboard.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

apps/skateboard/web/views/layout_view.ex
defmodule Skateboard.LayoutView do
  use Skateboard.Web, :view
end

apps/skateboard/web/views/page_view.ex
defmodule Skateboard.PageView do
  use Skateboard.Web, :view
end

apps/skateboard/web/views/registration_view.ex
defmodule Skateboard.RegistrationView do
  use Skateboard.Web, :view
end

apps/skateboard/web/views/session_view.ex
defmodule Skateboard.SessionView do
  use Skateboard.Web, :view
end

apps/skateboard/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>LettersMash</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <%= if logged_in?(@conn) do %>
              <script>window.userToken = "<%= current_user(@conn).id %>"</script>
              <li><%= current_user(@conn).name %></li>
              <li><%= link "Logout", to: session_path(@conn, :delete), method: :delete %></li>
            <% else %>
              <li><%= link "Login",    to: "/login" %></li>
              <li><%= link "Register", to: registration_path(@conn, :new) %></li>
            <% end %>
          </ul>
        </nav>
        <img src="images/logo.png"/ width="20%">
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

apps/skateboard/web/templates/page/index.html.eex
<div id="elm-container"></div>

apps/skateboard/web/templates/session/new.html.eex
<h2>Login</h2>

<%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %>
  <div class="form-group">
    <label>Name</label>
    <%= text_input f, :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Password</label>
    <%= password_input f, :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Login", class: "btn btn-primary" %>
  </div>
<% end %>